apiVersion: v1
kind: Namespace
metadata:
  name: redis

---

apiVersion: v1
kind: Service
metadata:
  name: redis-insight-service
  namespace: redis
spec:
  selector:
    app: redis-insight
  ports:
  - port: 5540
    targetPort: 5540
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-insight
  namespace: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-insight
  template:
    metadata:
      labels:
        app: redis-insight
    spec:
      containers:
        - name: redis-insight
          image: redis/redisinsight:latest
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: redis-insight
              mountPath: /data
          ports:
            - containerPort: 5540
              protocol: TCP
      volumes:
        - name: redis-insight
          emptyDir: {}


---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: redis-insight-ingress
  namespace: redis
spec:
  rules:
    - http:
        paths:
          - path: /redis-insight
            pathType: Prefix
            backend:
              service:
                name: redis-insight-service
                port:
                  number: 5540



